server:
  http:
    host: localhost
    port: 8081
    enableTLS: false
    correctTimeOut: 10000
  grpc:
    host: localhost
    port: 50051
    enableTLS: false
    correctTimeOut: 30000

database:
  driverName: mysql
  host: localhost
  port: 3306
  userName: root
  password: root123
  dbName: ecomerce
  sslMode: disable
  maxOpenConnections: 100
  maxIdleConnections: 10
  maxConnLifetime: 3600s
  maxConnIdleTime: 3600s

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  maxIdle: 10
  dialTimeout: 10s
  readTimeout: 10s
  writeTimeout: 10s

