server:
  grpc:
    host: localhost
    port: 8080
    enableTLS: false
    correctTimeOut: 30000

redis:
  db: 0
  maxIdle: 1024
  dialTimeout: 10s
  readTimeout: 10s
  writeTimeout: 10s
  readOnly: true
  routeRandomly: true
  maxRedirects: 3
  clusters:
    - "localhost:7001"
    - "localhost:7002"
    - "localhost:7003"
    - "localhost:7004"
    - "localhost:7005"
    - "localhost:7006"


