server:
  grpc:
    host: localhost
    port: 50052
    enableTLS: false
    correctTimeOut: 60000
  http:
    host: localhost
    port: 8081
    enableTLS: false
    correctTimeOut: 10000

grpcClient:
  host: 10.89.15.96
  port: 50051
  readTimeOut: 300s
  writeTimeOut: 300s

redis:
  db: 0
  maxIdle: 1024
  dialTimeout: 30s
  readTimeout: 30s
  writeTimeout: 30s
  readOnly: true
  routeRandomly: true
  maxRedirects: 10
  poolSize: 500
  minIdleConns: 6
  channel: account-balance-change
  clusters:
    - "localhost:7001"
    - "localhost:7002"
    - "localhost:7003"
    - "localhost:7004"
    - "localhost:7005"
    - "localhost:7006"
