# version: "3.1"

version: '3.8'

services:
  redis-node-1:
    image: redis:7.4
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip redis-node-1 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "7001:6379"
      - "17001:16379"
    volumes:
      - redis-node-1-data:/data
    networks:
      - redis-cluster
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-node-2:
    image: redis:7.4
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip redis-node-2 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "7002:6379"
      - "17002:16379"
    volumes:
      - redis-node-2-data:/data
    networks:
      - redis-cluster
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-node-3:
    image: redis:7.4
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip redis-node-3 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "7003:6379"
      - "17003:16379"
    volumes:
      - redis-node-3-data:/data
    networks:
      - redis-cluster
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-node-4:
    image: redis:7.4
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip redis-node-4 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "7004:6379"
      - "17004:16379"
    volumes:
      - redis-node-4-data:/data
    networks:
      - redis-cluster
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-node-5:
    image: redis:7.4
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip redis-node-5 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "7005:6379"
      - "17005:16379"
    volumes:
      - redis-node-5-data:/data
    networks:
      - redis-cluster
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-node-6:
    image: redis:7.4
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip redis-node-6 --cluster-announce-port 6379 --cluster-announce-bus-port 16379
    ports:
      - "7006:6379"
      - "17006:16379"
    volumes:
      - redis-node-6-data:/data
    networks:
      - redis-cluster
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-cluster-init:
    image: redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      - redis-cluster
    command: >
      bash -c "
      echo 'Waiting for redis nodes...' &&
      sleep 10 &&
      redis-cli --cluster create
      redis-node-1:6379
      redis-node-2:6379
      redis-node-3:6379
      redis-node-4:6379
      redis-node-5:6379
      redis-node-6:6379
      --cluster-replicas 1 --cluster-yes"

networks:
  redis-cluster:
    driver: bridge

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:
