// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.6.1
// source: proto/betting/betting.proto

package betting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BettingMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId     int64 `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Amount        int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BetId         int64 `protobuf:"varint,3,opt,name=betId,proto3" json:"betId,omitempty"`
	TransactionId int64 `protobuf:"varint,4,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *BettingMessageRequest) Reset() {
	*x = BettingMessageRequest{}
	mi := &file_proto_betting_betting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BettingMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettingMessageRequest) ProtoMessage() {}

func (x *BettingMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_betting_betting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettingMessageRequest.ProtoReflect.Descriptor instead.
func (*BettingMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_betting_betting_proto_rawDescGZIP(), []int{0}
}

func (x *BettingMessageRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *BettingMessageRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BettingMessageRequest) GetBetId() int64 {
	if x != nil {
		return x.BetId
	}
	return 0
}

func (x *BettingMessageRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *BettingMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BettingResponse) Reset() {
	*x = BettingResponse{}
	mi := &file_proto_betting_betting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettingResponse) ProtoMessage() {}

func (x *BettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_betting_betting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettingResponse.ProtoReflect.Descriptor instead.
func (*BettingResponse) Descriptor() ([]byte, []int) {
	return file_proto_betting_betting_proto_rawDescGZIP(), []int{1}
}

func (x *BettingResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BettingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_betting_betting_proto protoreflect.FileDescriptor

var file_proto_betting_betting_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2f,
	0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0xa7, 0x01, 0x0a, 0x15, 0x42, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x74, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x65, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x3f, 0x0a, 0x0f, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x5b, 0x0a, 0x0e, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x42,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x42,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f,
	0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_betting_betting_proto_rawDescOnce sync.Once
	file_proto_betting_betting_proto_rawDescData = file_proto_betting_betting_proto_rawDesc
)

func file_proto_betting_betting_proto_rawDescGZIP() []byte {
	file_proto_betting_betting_proto_rawDescOnce.Do(func() {
		file_proto_betting_betting_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_betting_betting_proto_rawDescData)
	})
	return file_proto_betting_betting_proto_rawDescData
}

var file_proto_betting_betting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_betting_betting_proto_goTypes = []any{
	(*BettingMessageRequest)(nil), // 0: betting.BettingMessageRequest
	(*BettingResponse)(nil),       // 1: betting.BettingResponse
}
var file_proto_betting_betting_proto_depIdxs = []int32{
	0, // 0: betting.BettingService.CreateBetting:input_type -> betting.BettingMessageRequest
	1, // 1: betting.BettingService.CreateBetting:output_type -> betting.BettingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_betting_betting_proto_init() }
func file_proto_betting_betting_proto_init() {
	if File_proto_betting_betting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_betting_betting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_betting_betting_proto_goTypes,
		DependencyIndexes: file_proto_betting_betting_proto_depIdxs,
		MessageInfos:      file_proto_betting_betting_proto_msgTypes,
	}.Build()
	File_proto_betting_betting_proto = out.File
	file_proto_betting_betting_proto_rawDesc = nil
	file_proto_betting_betting_proto_goTypes = nil
	file_proto_betting_betting_proto_depIdxs = nil
}
