// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: proto/transaction/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ac            int32                  `protobuf:"varint,1,opt,name=ac,proto3" json:"ac,omitempty"`
	Tx            int64                  `protobuf:"varint,2,opt,name=tx,proto3" json:"tx,omitempty"`
	Bab           int64                  `protobuf:"varint,3,opt,name=bab,proto3" json:"bab,omitempty"`
	Change        int64                  `protobuf:"varint,4,opt,name=change,proto3" json:"change,omitempty"`
	Baf           int64                  `protobuf:"varint,5,opt,name=baf,proto3" json:"baf,omitempty"`
	Type          int32                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Itx           int64                  `protobuf:"varint,8,opt,name=itx,proto3" json:"itx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionUpdate) Reset() {
	*x = TransactionUpdate{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionUpdate) ProtoMessage() {}

func (x *TransactionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionUpdate.ProtoReflect.Descriptor instead.
func (*TransactionUpdate) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionUpdate) GetAc() int32 {
	if x != nil {
		return x.Ac
	}
	return 0
}

func (x *TransactionUpdate) GetTx() int64 {
	if x != nil {
		return x.Tx
	}
	return 0
}

func (x *TransactionUpdate) GetBab() int64 {
	if x != nil {
		return x.Bab
	}
	return 0
}

func (x *TransactionUpdate) GetChange() int64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *TransactionUpdate) GetBaf() int64 {
	if x != nil {
		return x.Baf
	}
	return 0
}

func (x *TransactionUpdate) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TransactionUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionUpdate) GetItx() int64 {
	if x != nil {
		return x.Itx
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

var File_proto_transaction_transaction_proto protoreflect.FileDescriptor

var file_proto_transaction_transaction_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xad, 0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x61, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x61, 0x62, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x62, 0x61, 0x62, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x61, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x62, 0x61, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x74, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x69,
	0x74, 0x78, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x5d, 0x0a, 0x12, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x47, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x12, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_transaction_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_transaction_proto_rawDescData = file_proto_transaction_transaction_proto_rawDesc
)

func file_proto_transaction_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_transaction_transaction_proto_rawDescData)
	})
	return file_proto_transaction_transaction_proto_rawDescData
}

var file_proto_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_transaction_transaction_proto_goTypes = []any{
	(*TransactionUpdate)(nil), // 0: transaction.TransactionUpdate
	(*Empty)(nil),             // 1: transaction.Empty
}
var file_proto_transaction_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.TransactionService.UpdateTransaction:input_type -> transaction.TransactionUpdate
	1, // 1: transaction.TransactionService.UpdateTransaction:output_type -> transaction.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_transaction_transaction_proto_init() }
func file_proto_transaction_transaction_proto_init() {
	if File_proto_transaction_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_transaction_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_proto_transaction_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_transaction_proto = out.File
	file_proto_transaction_transaction_proto_rawDesc = nil
	file_proto_transaction_transaction_proto_goTypes = nil
	file_proto_transaction_transaction_proto_depIdxs = nil
}
