server:
  http:
    port: 8081
    enableTLS: false
    correctTimeOut: 10000
  grpc:
    port: 9081
    enableTLS: false
    correctTimeOut: 10000

redis:
  db: 0
  maxIdle: 1024
  dialTimeout: 10s
  readTimeout: 10s
  writeTimeout: 10s
  readOnly: true
  routeRandomly: true
  maxRedirects: 3
  clusters:
    - "localhost:7001"
    - "localhost:7002"
    - "localhost:7003"
    - "localhost:7004"
    - "localhost:7005"
    - "localhost:7006"

grpcClient:
  host: localhost
  port: 9081
  readTimeOut: 10s
  writeTimeOut: 10s

