server:
  http:
    port: 8081
    enableTLS: false
    correctTimeOut: 10000
  grpc:
    port: 9081
    enableTLS: false
    correctTimeOut: 10000

database:
  driverName: mysql
  host: localhost
  port: 3306
  userName: root
  password: root123
  dbName: ecomerce
  sslMode: disable
  maxOpenConnections: 100
  maxIdleConnections: 10
  maxConnLifetime: 3600s
  maxConnIdleTime: 3600s

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  maxIdle: 10
  dialTimeout: 10s
  readTimeout: 10s
  writeTimeout: 10s

grpcClient:
  host: localhost
  port: 9081
  readTimeOut: 10s
  writeTimeOut: 10s

nats:
  host: localhost
  port: 4222
  topics:
    orderTopic: order.topic
    productTopic: product.topic
    promotionTopic: promotion.topic
    userTopic: user.topic
